---
language: c
env:
  global:
    - secure: doqnexVja/vycDhxGTNlnGxybqY68+6Ddf5/IrqEbAHOM3G8LtKyejH54MsAkMNxSPlR3KxAB0kLnVQvs3Plt5iyGkjIyw/JDYHzznw2/XA7O/sOBNqvVgP89qeWBfM5xPnckSqOOMwVTouDenzzaWvkBUi2UQZ/vLyuJuxZa4Q0kWa3hanHqaiZjyrPbkRzNjuVcwyqbUQG7wzWsDk/N1R8WGEBrQFKPZ9Zoh6SM0vJaLf7RqnrHEFW4UbL8hkQb5oUrd7Gx/taYftjM0YLuro4/iHzuZIdAJ5qLS3c9XYkfhmrfuRPXGdB6BkXKBdWsWnaCh69O6iYBWgAmJeL73xtW3EQRVGCilVnxcA/riDavLs+cdnVnhb6ePuBTRr8fyw6TRCgKM42YiX+Be0JESfPG/6D/CtktMJ3KYW8WWkNj3K71WHVS6xAXqo3/6PznmurCSxlbEym1me944V7LHmUy5q0h+oFS8Gel5PbguoCkEhxM07q6+XijhBFHhErvtxL3NPcqeLKZmo0MCaS7EzoY60d2kZixf0mHD7O6D4nktRnePIeKrsVtAK4Yi+X0cHMXNso45ew+KvpZzWBHZZVEA+M8fkp3/T3kq52WglLTNW5wnun9tduP6rJPLiSOEgP1cY6ehdCIlrn+n+QyMg8Ap25UeHUBxyUeoOpA9Y=
script: packer build dev.json
